---
standardLibrary:
  name: "standard-library"
config:
  fileName: "pipeline.yml"
proxy:
  excludes:
    - ".dev.interac.ca"
    - ".dev1.interac.ca"
    - ".dev2.interac.ca"
    - ".sit1.interac.ca"
    - ".sit2.interac.ca"
    - ".sit3.interac.ca"
    - ".sit4.interac.ca"
    - ".sit5.interac.ca"
workspace:
  name: "standard-workspace"
color:
  white: "FFFFFF"
  red: "FF0000"
  yellow: "FFCC00"
  green: "00CC00"
  blue: "0000FF"
agent:
  label:
    default: "default"
branch:
  master: "master"
  release: "release"
  hotfix: "hotfix"
delimiter:
  comma: ","
repository:
  user: "etjenartif"
  maven:
    snapshots: "interac-maven-snapshots"
    releases: "interac-maven-releases"
  docker:
    snapshots: "interac-docker-snapshots"
    releases: "interac-docker-releases"
build:
  tool:
    maven: "maven"
    gradle: "gradle"
    python: "python"
  sdk:
    android: "android"
version:
  snapshot:
    suffix: "SNAPSHOT"
pipeline:
  type:
    snapshots: "SNAPSHOTS"
    releases: "RELEASES"
    rollback: "ROLLBACK"
    deploy: "DEPLOY"
  deploy:
    repo: "interac/deployments"
    config:
      defaultDir: "./src/main/deploy/"
    pattern:
      deployCompose: "deploy-compose"
      deployK8s: "deploy-k8s"
      deployCdn: "deploy-cdn"
      # legacy
      dockerCompose: "docker-compose"
      # legacy
      dockerComposeSsh: "docker-compose-ssh"
      # legacy
      esgDeploy: "esg-deploy-ssh"
    platform:
      # Azure Stack Hub (on-prem, CGI datacenter)
      ash: "ASH"
      # OpenShift Cloud (on-prem, CGI datacenter)
      osc: "OSC"
      # Azure Public Cloud
      apc: "APC"
      # CGI datacenter (on-prem, legacy)
      cgi: "CGI"
      #TODO: remove - Oracle Cloud Infrastructure
      oci: "OCI"
    environment:
      dev: "DEV"
      sim: "SIM"
      simdev1: "SIMDEV1"
      dev1: "DEV1"
      dev2: "DEV2"
      qasit: "QASIT"
      qa1: "QA1"
      simqa1: "SIMQA1"
      sit1: "SIT1"
      sit2: "SIT2"
      sit3: "SIT3"
      sit4: "SIT4"
      sit5: "SIT5"
      perf: "PERF"
      setest: "SETEST"
      uat1: "UAT1"
      uat2: "UAT2"
      beta: "BETA"
      fit: "FIT"
      preprod: "PREPROD"
      prod: "PROD"
      prodDdcaz2: "PROD_DDCAZ2"
      prodMdcaz1: "PROD_MDCAZ1"
      prodAll: "PROD_ALL"
    user:
      dev: "app_dev"
      qasit: "app_qasit"
      perf: "app_perf"
      setest: "app_perf"
      beta: "app_beta"
      fit: "app_fiint"
      prod: "app_prod"
    param:
      uiSeparator: "____________________________________________________________________________________________________"
  notification:
    email:
      mimeType: "text/html"
      from: "\"Jenkins\" <jenkins@dev.interac.ca>"
      recipients:
        validDomains:
          - "interac.ca"
  status:
    success:
      code: "SUCCESS"
      notification:
        color: "00CC00"
        message: "Pipeline completed and is SUCCESSFUL"
        icon: "✅"
    failure:
      code: "FAILURE"
      notification:
        color: "FF0000"
        message: "Pipeline FAILED"
        icon: "❌"
    unstable:
      code: "UNSTABLE"
      notification:
        color: "FFCC00"
        message: "Pipeline completed but is UNSTABLE"
        icon: "⚠️"
    blocked:
      code: "BLOCKED"
      notification:
        color: "CC00CC"
        message: "Pipeline is BLOCKED"
        icon: "⛔"
